"""Add teacher leave document fields

Revision ID: 099e5c53fe4a
Revises: 6518f0d778a7
Create Date: 2026-08-29 22:27:46.637307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099e5c53fe4a'
down_revision = '6518f0d778a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_attendance_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_attendance_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_attendance_faculty_user_id'), ['faculty_user_id'], unique=False)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('alternate_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('responsibility_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('supporting_document', sa.String(length=500), nullable=True))

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notices_created_by'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_notices_created_by'), 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_column('supporting_document')
        batch_op.drop_column('responsibility_note')
        batch_op.drop_column('alternate_email')
        batch_op.drop_column('contact_number')

    with op.batch_alter_table('faculty_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_attendance_faculty_user_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_attendance_department_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_attendance_date'))

    # ### end Alembic commands ###
